from core.enums import BaseEnum


class SpareTypes(BaseEnum):
    BRAKE_SYSTEM = "BRAKE_SYSTEM"
    ELECTRICAL_SYSTEM = "ELECTRICAL_SYSTEM"
    HYDRAULIC_SYSTEM = "HYDRAULIC_SYSTEM"
    MOTORS_AND_TRANSMISSION = "MOTORS_AND_TRANSMISSION"
    BODY = "BODY"
    OTHER = "OTHER"
