# Generated by Django 4.0.5 on 2022-06-22 08:57

import core.model_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('type', models.CharField(choices=[('BRAKE_SYSTEM', 'BRAKE_SYSTEM'), ('ELECTRICAL_SYSTEM', 'ELECTRICAL_SYSTEM'), ('HYDRAULIC_SYSTEM', 'HYDRAULIC_SYSTEM'), ('MOTORS_AND_TRANSMISSION', 'MOTORS_AND_TRANSMISSION'), ('BODY', 'BODY'), ('OTHER', 'OTHER')], max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=256, verbose_name='description')),
                ('photo', models.ImageField(upload_to=core.model_functions.generate_upload_to_path, verbose_name='photo')),
            ],
        ),
    ]
